import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useAuthenticate } from '../hooks/authentication';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { user } = useAuthenticate();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h2>{user?.uid || 'ログインしてないよ！'}</h2>
      <Link href='/page2'>
        <a>go to page2</a>
      </Link>
    </div>
  );
};

export default Home;
